apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-apps
  namespace: argocd
  annotations:
    "helm.sh/resource-policy": keep
    argocd.argoproj.io/sync-wave: "-20"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Basic apps for operating the cluster
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
