apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-12"
    notifications.argoproj.io/subscribe.on-health-degraded.slack: platform-engineering-alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: platform-engineering-alerts
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: cluster-apps
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.13.*
    helm:
      releaseName: cert-manager
      values: |
{{ .Files.Get "app-values/cert-manager.yaml" | trim | indent 8 }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - ApplyOutOfSyncOnly=true

